let numero1;
let numero1_parse;
let numero2_parse;
let numero2;
numero1 = window.prompt ("Ingrese un número");
numero2 = window.prompt ("Ingrese un número");
numero1_parse=parseFloat(numero1);
numero2_parse=parseFloat(numero2);
let resultado=numero1_parse+numero2_parse;
parseFloat(resultado);
document.write(resultado);
